[2022-11-18T21:07:22.521+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2022-11-18T21:07:13.832728+00:00 [queued]>
[2022-11-18T21:07:22.540+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2022-11-18T21:07:13.832728+00:00 [queued]>
[2022-11-18T21:07:22.540+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T21:07:22.541+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T21:07:22.541+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T21:07:22.575+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): ingest> on 2022-11-18 21:07:13.832728+00:00
[2022-11-18T21:07:22.585+0000] {standard_task_runner.py:55} INFO - Started process 772 to run task
[2022-11-18T21:07:22.604+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'manual__2022-11-18T21:07:13.832728+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpwf1ngbh1']
[2022-11-18T21:07:22.608+0000] {standard_task_runner.py:83} INFO - Job 81: Subtask ingest
[2022-11-18T21:07:22.764+0000] {task_command.py:376} INFO - Running <TaskInstance: LocalIngestionDag.ingest manual__2022-11-18T21:07:13.832728+00:00 [running]> on host b8836091f311
[2022-11-18T21:07:22.837+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-18T21:07:22.893+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T21:07:13.832728+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-18T21:07:13.832728+00:00
[2022-11-18T21:07:22.895+0000] {logging_mixin.py:137} INFO - ??? /opt/***/output_2022-11.csv.gz
[2022-11-18T21:07:22.896+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 12, in ingest_callable
    engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{db}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 530, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 715, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 771, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'pgdatabase'
[2022-11-18T21:07:22.910+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20221118T210713, start_date=20221118T210722, end_date=20221118T210722
[2022-11-18T21:07:22.932+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 81 for task ingest (invalid literal for int() with base 10: 'pgdatabase'; 772)
[2022-11-18T21:07:22.978+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T21:07:23.005+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
