[2022-11-19T17:44:08.432+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: green_taxi_data_v1.download_dataset_task scheduled__2022-10-02T07:00:00+00:00 [queued]>
[2022-11-19T17:44:08.475+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: green_taxi_data_v1.download_dataset_task scheduled__2022-10-02T07:00:00+00:00 [queued]>
[2022-11-19T17:44:08.475+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-19T17:44:08.475+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-19T17:44:08.476+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-19T17:44:08.592+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-10-02 07:00:00+00:00
[2022-11-19T17:44:08.603+0000] {standard_task_runner.py:55} INFO - Started process 59254 to run task
[2022-11-19T17:44:08.614+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'green_taxi_data_v1', 'download_dataset_task', 'scheduled__2022-10-02T07:00:00+00:00', '--job-id', '403', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_homework.py', '--cfg-path', '/tmp/tmpbzy5t8ep']
[2022-11-19T17:44:08.622+0000] {standard_task_runner.py:83} INFO - Job 403: Subtask download_dataset_task
[2022-11-19T17:44:08.799+0000] {task_command.py:376} INFO - Running <TaskInstance: green_taxi_data_v1.download_dataset_task scheduled__2022-10-02T07:00:00+00:00 [running]> on host b8836091f311
[2022-11-19T17:44:08.905+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-19T17:44:09.056+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=green_taxi_data_v1
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-10-02T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-02T07:00:00+00:00
[2022-11-19T17:44:09.058+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-19T17:44:09.059+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-10.parquet > /opt/***/green_tripdata_2022-10.parquet']
[2022-11-19T17:44:09.102+0000] {subprocess.py:86} INFO - Output:
[2022-11-19T17:44:09.547+0000] {subprocess.py:93} INFO - curl: (22) The requested URL returned error: 403
[2022-11-19T17:44:09.562+0000] {subprocess.py:97} INFO - Command exited with return code 22
[2022-11-19T17:44:09.598+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-19T17:44:09.614+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=green_taxi_data_v1, task_id=download_dataset_task, execution_date=20221002T070000, start_date=20221119T174408, end_date=20221119T174409
[2022-11-19T17:44:09.660+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 403 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 22.; 59254)
[2022-11-19T17:44:09.722+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-19T17:44:09.807+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
