[2022-11-18T20:08:51.874+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget manual__2022-11-18T20:08:50.465497+00:00 [queued]>
[2022-11-18T20:08:51.902+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget manual__2022-11-18T20:08:50.465497+00:00 [queued]>
[2022-11-18T20:08:51.902+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T20:08:51.902+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T20:08:51.903+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T20:08:51.933+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): wget> on 2022-11-18 20:08:50.465497+00:00
[2022-11-18T20:08:51.942+0000] {standard_task_runner.py:55} INFO - Started process 69183 to run task
[2022-11-18T20:08:51.949+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'manual__2022-11-18T20:08:50.465497+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpm52abz7c']
[2022-11-18T20:08:51.950+0000] {standard_task_runner.py:83} INFO - Job 66: Subtask wget
[2022-11-18T20:08:52.048+0000] {task_command.py:376} INFO - Running <TaskInstance: LocalIngestionDag.wget manual__2022-11-18T20:08:50.465497+00:00 [running]> on host 2f138cf78b7c
[2022-11-18T20:08:52.103+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-18T20:08:52.169+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T20:08:50.465497+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-18T20:08:50.465497+00:00
[2022-11-18T20:08:52.171+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-18T20:08:52.172+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo " 2022-11-18 " " 2022-11-18T20:08:50.465497+00:00 "" ']
[2022-11-18T20:08:52.191+0000] {subprocess.py:86} INFO - Output:
[2022-11-18T20:08:52.194+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `"'
[2022-11-18T20:08:52.194+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2022-11-18T20:08:52.195+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-18T20:08:52.218+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-18T20:08:52.228+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=wget, execution_date=20221118T200850, start_date=20221118T200851, end_date=20221118T200852
[2022-11-18T20:08:52.263+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 66 for task wget (Bash command failed. The command returned a non-zero exit code 2.; 69183)
[2022-11-18T20:08:52.286+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T20:08:52.340+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
