[2022-11-18T19:58:18.601+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget manual__2022-11-18T19:58:17.642454+00:00 [queued]>
[2022-11-18T19:58:18.616+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget manual__2022-11-18T19:58:17.642454+00:00 [queued]>
[2022-11-18T19:58:18.616+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T19:58:18.616+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T19:58:18.616+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T19:58:18.635+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): wget> on 2022-11-18 19:58:17.642454+00:00
[2022-11-18T19:58:18.642+0000] {standard_task_runner.py:55} INFO - Started process 68657 to run task
[2022-11-18T19:58:18.649+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'manual__2022-11-18T19:58:17.642454+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpoir7t9tq']
[2022-11-18T19:58:18.650+0000] {standard_task_runner.py:83} INFO - Job 63: Subtask wget
[2022-11-18T19:58:18.748+0000] {task_command.py:376} INFO - Running <TaskInstance: LocalIngestionDag.wget manual__2022-11-18T19:58:17.642454+00:00 [running]> on host 2f138cf78b7c
[2022-11-18T19:58:18.886+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T19:58:17.642454+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-18T19:58:17.642454+00:00
[2022-11-18T19:58:18.887+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-18T19:58:18.888+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz -O /opt/***/output.csv.gz && gunzip /opt/***/output.csv.gz']
[2022-11-18T19:58:18.904+0000] {subprocess.py:86} INFO - Output:
[2022-11-18T19:58:18.913+0000] {subprocess.py:93} INFO - /bin/bash: line 1: wget: command not found
[2022-11-18T19:58:18.914+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-11-18T19:58:18.932+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-18T19:58:18.940+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=wget, execution_date=20221118T195817, start_date=20221118T195818, end_date=20221118T195818
[2022-11-18T19:58:18.963+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 63 for task wget (Bash command failed. The command returned a non-zero exit code 127.; 68657)
[2022-11-18T19:58:18.980+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-18T19:58:19.020+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
