[2022-11-19T17:44:06.032+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: green_taxi_data_v1.download_dataset_task scheduled__2022-09-02T07:00:00+00:00 [queued]>
[2022-11-19T17:44:06.051+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: green_taxi_data_v1.download_dataset_task scheduled__2022-09-02T07:00:00+00:00 [queued]>
[2022-11-19T17:44:06.051+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-19T17:44:06.051+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-19T17:44:06.051+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-19T17:44:06.090+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-09-02 07:00:00+00:00
[2022-11-19T17:44:06.101+0000] {standard_task_runner.py:55} INFO - Started process 59248 to run task
[2022-11-19T17:44:06.118+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'green_taxi_data_v1', 'download_dataset_task', 'scheduled__2022-09-02T07:00:00+00:00', '--job-id', '402', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_homework.py', '--cfg-path', '/tmp/tmpt4h8slz5']
[2022-11-19T17:44:06.122+0000] {standard_task_runner.py:83} INFO - Job 402: Subtask download_dataset_task
[2022-11-19T17:44:06.279+0000] {task_command.py:376} INFO - Running <TaskInstance: green_taxi_data_v1.download_dataset_task scheduled__2022-09-02T07:00:00+00:00 [running]> on host b8836091f311
[2022-11-19T17:44:06.441+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-11-19T17:44:06.679+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=green_taxi_data_v1
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-02T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-02T07:00:00+00:00
[2022-11-19T17:44:06.681+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-19T17:44:06.682+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSLf https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-09.parquet > /opt/***/green_tripdata_2022-09.parquet']
[2022-11-19T17:44:06.726+0000] {subprocess.py:86} INFO - Output:
[2022-11-19T17:44:07.166+0000] {subprocess.py:93} INFO - curl: (22) The requested URL returned error: 403
[2022-11-19T17:44:07.167+0000] {subprocess.py:97} INFO - Command exited with return code 22
[2022-11-19T17:44:07.211+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-11-19T17:44:07.228+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=green_taxi_data_v1, task_id=download_dataset_task, execution_date=20220902T070000, start_date=20221119T174406, end_date=20221119T174407
[2022-11-19T17:44:07.302+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 402 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 22.; 59248)
[2022-11-19T17:44:07.382+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-19T17:44:07.499+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
